### PR TITLE
Fix Data Attributes Selectors

### PR DESCRIPTION
**Pull request by Publicker**
This pull request addresses an issue (#11) where data attributes were not functioning as expected. 

The selectors for data attributes have been fixed and now operate correctly. This has been tested with TailwindCSS data attributes, and the functionality has been confirmed.

Please review these changes to ensure that the data attributes are now functioning as intended.

### CODE REVIEW

**Comment by n4j1Br4ch1D** [comment]
Hi @Publicker  thanks for PR, I have been taking some time to look at the new features in tailwinds, and found some CSS classes that don't obfuscate for many reasons but mainly due to: the regex used to parse CSS selectors. 
some example:
```jsx
 {/* Solved */}
      {/* only removes  CSS [attribute*=value] selectors when the `[` is not preceded by `-\`. 
       thus it avoids tailwind`s arbitrary values, & data attributes */}
      {/* 
        .totest[href="value"] {
           ...
        }
     */}
      <span class="totest">1</span> 
      <span class="pt-[100px]">2</span>
      
      <span class="data-[size=large]:p-8">3</span>
      <span class="data-[href='active']:bg-green-100">4</span>
      <span class="data-[size=large]:p-8">5</span>
      <span class="group-data-[status='active']:text-green-700">6</span>

{/* Not yet solved */}

      {/* problem with parsing . as a new class */}
      <span class="group-[.is-published]:block">8</span>
      <span class="peer-[.is-dirty]:peer-required:block">10</span>
     
      {/* prblm with (*) beign removed */}
      <span class="group-[:nth-of-type(3)_&]:block">9</span>
      <span class="[@supports(display:grid)]:grid">7</span>
      <span class="[@media(any-hover:hover){&:hover}]:opacity-100">12</span>
```
As per your commits unfortunately your solution only works for your situation & won't work for CSS [attribute*=value]. `.totest` as an example above.

So ill make a commit for you in a minute to test my new solution, and ill open issue/issues for the rest `not yet solved`

**Comment by Publicker** [comment]
> @Publicker plz check the solution : [a71e8b7](https://github.com/n4j1Br4ch1D/postcss-obfuscator/commit/a71e8b747a505971e492123ee9f5f4f901a3a2ad) before i merge

Thanks for the explanation. I just tested the solution in the mentioned commit and seems to be working for data attributes 👍🏻.

**Comment by n4j1Br4ch1D** [comment]
> > @Publicker plz check the solution : [a71e8b7](https://github.com/n4j1Br4ch1D/postcss-obfuscator/commit/a71e8b747a505971e492123ee9f5f4f901a3a2ad) before i merge
> 
> @n4j1Br4ch1D Thanks for the explanation. I just tested the solution in the mentioned commit and seems to be working for data attributes 👍🏻.

@Publicker  glad it does: only #14 is left it will be solved soon, and all fixes will be released on the next version soon. 
Plz, consider giving the project a `start`  to keep it going.

**Comment by Publicker** [comment]
> > > @Publicker plz check the solution : [a71e8b7](https://github.com/n4j1Br4ch1D/postcss-obfuscator/commit/a71e8b747a505971e492123ee9f5f4f901a3a2ad) before i merge
> > 
> > 
> > @n4j1Br4ch1D Thanks for the explanation. I just tested the solution in the mentioned commit and seems to be working for data attributes 👍🏻.
> 
> @Publicker glad it does: only #14 is left it will be solved soon, and all fixes will be released on the next version soon. Plz, consider giving the project a `start` to keep it going.

@n4j1Br4ch1D I'm sure that will be ready sooner than I expect! Keep the good work going!

**Pull request merged**
